export const GAME_CONFIG = {
  // ── CORE GAMEPLAY ──
  MAX_PLAYERS: 20,
  RESPAWN_COOLDOWN: 0, 
  VICTORY_TIMER: 20000,    // 20 detik countdown kemenangan
  PLAYER_RADIUS: 35,
  
  // ── PHYSICS ──
  GRAVITY: 0.15,          // Reduced significantly for floating feel
  POSITION_ITERATIONS: 1,
  VELOCITY_ITERATIONS: 1,
  PHYSICS_STEP: 1000 / 60,
  KNOCKBACK_FORCE: 0.03,  
  WALL_THICKNESS: 200,
  
  // ── AI & LOGIC ──
  AI_DECISION_INTERVAL: 500, // Reduced AI frequency to save CPU
  
  // ── AI & MOVEMENT ──
  AI_IMPULSE_FORCE_MIN: 0.015, 
  AI_IMPULSE_FORCE_VAR: 0.01, 
  AI_BEHAVIOR_INTERVAL: 4000, // Slower decision making
  CHAT_BOOST_FORCE: 0.05,     
  LIKE_BOOST_MULTIPLIER: 1.2,
  
  MIN_SPEED: 2,
  MAX_SPEED: 8,             
  MAX_ANGULAR_VELOCITY: 0.1, 
  
  // ── VISUALS ──
  SHAKE_INTENSITY: 0,
  MAX_TRAIL_LENGTH: 8,
  SWORD_TRAIL_LENGTH: 6,
  ARENA_GRID_SIZE: 120,
  HIT_COOLDOWN: 600,
  HIT_FLASH_DURATION: 300,
  
  // ── ARENA ──
  ARENA_MARGIN: 5,
  HUD_ROW_HEIGHT: 60,
  HUD_ITEMS_PER_ROW: 10,
  HUD_ICON_SIZE: 40,
};
