export const GAME_CONFIG = {
  // ── CORE GAMEPLAY ──
  MAX_PLAYERS: 50,
  RESPAWN_COOLDOWN: 10000, // ms
  VICTORY_TIMER: 10000,    // ms
  PLAYER_RADIUS: 35,
  
  // ── PHYSICS ──
  GRAVITY: 0.8,
  POSITION_ITERATIONS: 10,
  VELOCITY_ITERATIONS: 10,
  KNOCKBACK_FORCE: 0.06,
  WALL_THICKNESS: 200,
  
  // ── AI & MOVEMENT ──
  AI_IMPULSE_FORCE_MIN: 0.08,
  AI_IMPULSE_FORCE_VAR: 0.07,
  AI_BEHAVIOR_INTERVAL: 800, // ms base
  CHAT_BOOST_FORCE: 0.12,
  LIKE_BOOST_MULTIPLIER: 1.5,
  
  MIN_SPEED: 7,
  MAX_SPEED: 20,
  MAX_ANGULAR_VELOCITY: 0.18,
  
  // ── VISUALS ──
  SHAKE_INTENSITY: 10,
  MAX_TRAIL_LENGTH: 8,
  HIT_COOLDOWN: 600,
  HIT_FLASH_DURATION: 300,
  
  // ── ARENA ──
  ARENA_MARGIN: 20,
  HUD_ROW_HEIGHT: 60,
  HUD_ITEMS_PER_ROW: 10,
  HUD_ICON_SIZE: 40,
};
