export const GAME_CONFIG = {
  // ── CORE GAMEPLAY ──
  MAX_PLAYERS: 9999,
  RESPAWN_COOLDOWN: 0, 
  VICTORY_TIMER: 20000,    // 20 detik countdown kemenangan
  PLAYER_RADIUS: 35,
  
  // ── PHYSICS ──
  GRAVITY: 0.35,          // Reduced from 0.8 for higher verticality
  POSITION_ITERATIONS: 10, 
  VELOCITY_ITERATIONS: 10,
  KNOCKBACK_FORCE: 0.05,  
  WALL_THICKNESS: 200,
  
  // ── AI & MOVEMENT ──
  AI_IMPULSE_FORCE_MIN: 0.06, 
  AI_IMPULSE_FORCE_VAR: 0.04, 
  AI_BEHAVIOR_INTERVAL: 1000, 
  CHAT_BOOST_FORCE: 0.1,     
  LIKE_BOOST_MULTIPLIER: 1.4,
  
  MIN_SPEED: 5,
  MAX_SPEED: 18,             
  MAX_ANGULAR_VELOCITY: 0.14, 
  
  // ── VISUALS ──
  SHAKE_INTENSITY: 0,
  MAX_TRAIL_LENGTH: 8,
  HIT_COOLDOWN: 600,
  HIT_FLASH_DURATION: 300,
  
  // ── ARENA ──
  ARENA_MARGIN: 20,
  HUD_ROW_HEIGHT: 60,
  HUD_ITEMS_PER_ROW: 10,
  HUD_ICON_SIZE: 40,
};
